version: '3'

services:
    mysqldb:
        build: ./config/db/
        image: mysql
        container_name: karyakita_global_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd|mysql
            MYSQL_DATABASE: karyakita_dev
            MYSQL_USER: mygetzu
            MYSQL_PASSWORD: P@ssw0rd|mysql
#        volumes:
#        - mysql-data:/var/lib/mysql
        ports:
        - 33060:33060
        networks:
            app-network:
                ipv4_address: 192.168.30.10

    service_karya:
        build: ./services/karya-service/
        container_name: karyakita_service_karya
        restart: unless-stopped
        env_file: .env
        ports:
        - 9001:80
        volumes:
        - './services/karya-service:/usr/src/app'
        networks:
            app-network:
                ipv4_address: 192.168.30.11
        depends_on:
          - mysqldb
#        command: [ "./wait-for.sh", "0.0.0.0:33060", "--", "node", "--inspect=0.0.0.0", "/usr/src/app/app.js" ]

    service_designer:
      build: ./services/designer-service/
      container_name: karyakita_service_designer
      restart: unless-stopped
      env_file: .env
      ports:
      - 9002:80
      volumes:
      - './services/designer-service:/usr/src/app'
      networks:
        app-network:
          ipv4_address: 192.168.30.12
      depends_on:
      - mysqldb
#        command: [ "./wait-for.sh", "0.0.0.0:33060", "--", "node", "--inspect=0.0.0.0", "/usr/src/app/app.js" ]

    service_user:
      build: ./services/user-service/
      container_name: karyakita_service_user
      restart: unless-stopped
      env_file: .env
      ports:
      - 9003:80
      volumes:
      - './services/user-service:/usr/src/app'
      networks:
        app-network:
          ipv4_address: 192.168.30.13
      depends_on:
      - mysqldb
#        command: [ "./wait-for.sh", "0.0.0.0:33060", "--", "node", "--inspect=0.0.0.0", "/usr/src/app/app.js" ]

    service_transaction:
      build: ./services/transaction-service/
      container_name: karyakita_service_transaction
      restart: unless-stopped
      env_file: .env
      ports:
      - 9004:80
      volumes:
      - './services/transaction-service:/usr/src/app'
      networks:
        app-network:
          ipv4_address: 192.168.30.14
      depends_on:
      - mysqldb
#        command: [ "./wait-for.sh", "0.0.0.0:33060", "--", "node", "--inspect=0.0.0.0", "/usr/src/app/app.js" ]

networks:
    app-network:
        driver: bridge
        ipam:
          config:
              - subnet : 192.168.30.0/24

volumes:
    mysql-data:
